// <auto-generated />
using System;
using BitMagnetRssImporter.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BitMagnetRssImporter.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260129170415_AddInjestionRunsAndHtmlTrackers")]
    partial class AddInjestionRunsAndHtmlTrackers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("BitMagnetRssImporter.Models.HtmlSeenItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InfoHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long>("TrackerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrackerId", "ItemKey")
                        .IsUnique();

                    b.ToTable("HtmlSeenItems");
                });

            modelBuilder.Entity("BitMagnetRssImporter.Models.HtmlTracker", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DetailLinkSelector")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InfoHashRegex")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastCheckedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastRunId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxPagesPerRun")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NextPageSelector")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("PollIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RowSelector")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("StartUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("StopAfterSeenStreak")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TitleSelector")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastRunId");

                    b.ToTable("HtmlTrackers");
                });

            modelBuilder.Entity("BitMagnetRssImporter.Models.IngestionRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Candidates")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("HeartbeatAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HttpStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Imported")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemsParsed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemsScanned")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewItems")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PagesVisited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("SeenStreak")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkippedNoInfoHash")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkippedSeen")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SourceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceType", "SourceId", "IsActive");

                    b.HasIndex("SourceType", "SourceId", "StartedAt");

                    b.ToTable("IngestionRuns");
                });

            modelBuilder.Entity("BitMagnetRssImporter.Models.RssFeed", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastCheckedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastEtag")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastRunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PollIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastRunId");

                    b.HasIndex("Url");

                    b.ToTable("RssFeeds");
                });

            modelBuilder.Entity("BitMagnetRssImporter.Models.RssFeedRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Candidates")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<long>("FeedId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HttpStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Imported")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemsParsed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewItems")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkippedNoInfoHash")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkippedSeen")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FeedId", "StartedAt");

                    b.ToTable("RssFeedRuns");
                });

            modelBuilder.Entity("BitMagnetRssImporter.Models.RssSeenItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("FeedId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InfoHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FeedId", "ItemKey")
                        .IsUnique();

                    b.ToTable("RssSeenItems");
                });

            modelBuilder.Entity("BitMagnetRssImporter.Models.HtmlTracker", b =>
                {
                    b.HasOne("BitMagnetRssImporter.Models.IngestionRun", "LastRun")
                        .WithMany()
                        .HasForeignKey("LastRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LastRun");
                });

            modelBuilder.Entity("BitMagnetRssImporter.Models.RssFeed", b =>
                {
                    b.HasOne("BitMagnetRssImporter.Models.IngestionRun", "LastRun")
                        .WithMany()
                        .HasForeignKey("LastRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LastRun");
                });

            modelBuilder.Entity("BitMagnetRssImporter.Models.RssFeedRun", b =>
                {
                    b.HasOne("BitMagnetRssImporter.Models.RssFeed", "Feed")
                        .WithMany()
                        .HasForeignKey("FeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feed");
                });

            modelBuilder.Entity("BitMagnetRssImporter.Models.RssSeenItem", b =>
                {
                    b.HasOne("BitMagnetRssImporter.Models.RssFeed", "Feed")
                        .WithMany()
                        .HasForeignKey("FeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feed");
                });
#pragma warning restore 612, 618
        }
    }
}
