// <auto-generated />
using System;
using BitMagnetRssImporter.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BitMagnetRssImporter.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260129143437_AddRssFeedRuns")]
    partial class AddRssFeedRuns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("BitMagnetRssImporter.Models.RssFeed", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastCheckedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastEtag")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastRunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PollIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastRunId");

                    b.HasIndex("Url");

                    b.ToTable("RssFeeds");
                });

            modelBuilder.Entity("BitMagnetRssImporter.Models.RssFeedRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Candidates")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<long>("FeedId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HttpStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Imported")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemsParsed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewItems")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkippedNoInfoHash")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkippedSeen")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FeedId", "StartedAt");

                    b.ToTable("RssFeedRuns");
                });

            modelBuilder.Entity("BitMagnetRssImporter.Models.RssSeenItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("FeedId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InfoHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FeedId", "ItemKey")
                        .IsUnique();

                    b.ToTable("RssSeenItems");
                });

            modelBuilder.Entity("BitMagnetRssImporter.Models.RssFeed", b =>
                {
                    b.HasOne("BitMagnetRssImporter.Models.RssFeedRun", "LastRun")
                        .WithMany()
                        .HasForeignKey("LastRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LastRun");
                });

            modelBuilder.Entity("BitMagnetRssImporter.Models.RssFeedRun", b =>
                {
                    b.HasOne("BitMagnetRssImporter.Models.RssFeed", "Feed")
                        .WithMany()
                        .HasForeignKey("FeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feed");
                });

            modelBuilder.Entity("BitMagnetRssImporter.Models.RssSeenItem", b =>
                {
                    b.HasOne("BitMagnetRssImporter.Models.RssFeed", "Feed")
                        .WithMany()
                        .HasForeignKey("FeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feed");
                });
#pragma warning restore 612, 618
        }
    }
}
